# Generated by Django 5.1 on 2024-08-12 17:23

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUser',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('municipality', models.CharField(choices=[('अर्जुनधारा', 'अर्जुनधारा'), ('कन्काई', 'कन्काई')], max_length=200)),
                ('ward', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('7', '7'), ('8', '8')], max_length=50)),
                ('tole', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=50)),
                ('member_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+977', max_length=128, region=None)),
                ('member_type', models.CharField(choices=[('क वर्ग', 'क वर्ग'), ('ख वर्ग', 'ख वर्ग')], max_length=50)),
                ('approved_by', models.CharField(default='', max_length=200)),
                ('approved_by_position', models.CharField(choices=[('अध्यक्ष', 'अध्यक्ष'), ('उपाध्यक्ष', 'उपाध्यक्ष')], default='', max_length=100)),
                ('date_approved', models.DateField()),
            ],
        ),
    ]
