# Generated by Django 5.1 on 2024-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_chetryasamiti_karyasamiti_sallakarsamiti_tolesamiti'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChetriyaSamiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='chetriyasamiti_images')),
                ('area', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LekhaSamiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='lekhasamiti_images')),
            ],
        ),
        migrations.DeleteModel(
            name='ChetryaSamiti',
        ),
        migrations.AlterField(
            model_name='tolesamiti',
            name='image',
            field=models.ImageField(upload_to='tolesamiti_images'),
        ),
    ]
