# Generated by Django 5.1 on 2024-08-13 16:55

import ourapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0005_gallery_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=ourapp.models.get_upload_to),
        ),
    ]
